CREATE TABLE FAQ_BOARD(
	FAQ_SEQ NUMBER NOT NULL,
	CATEGORY VARCHAR2(20),
	REG_ID VARCHAR2(50) NOT NULL,
	REG_DT DATE NOT NULL,
	MOD_DT DATE NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	VIEW_CNT NUMBER NOT NULL
);

SELECT * FROM FAQ_BOARD;

--DROP TABLE FAQ_BOARD;

COMMIT;

--시퀀스 아이디 발번
CREATE SEQUENCE FAQ_SEQ_TABLE;


INSERT INTO FAQ_BOARD(FAQ_SEQ, CATEGORY, REG_ID, REG_DT, MOD_DT, TITLE, CONTENT, VIEW_CNT)
VALUES(FAQ_SEQ_TABLE.NEXTVAL, '개인정보', 'adminonly', SYSDATE, SYSDATE, '비밀번호를 잊어버렸어요!',
	'비밀번호 분실 시 회원정보에서 본인인증 절차를 거치면 변경이 가능합니다.', 0);

COMMIT;

SELECT * FROM FAQ_BOARD ORDER BY FAQ_SEQ DESC;

--SELECT * FROM NOTICE_BOARD WHERE NOTICE_SEQ=?