CREATE TABLE QA_BOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,	
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REG_ID VARCHAR2(50) NOT NULL,
	REGDATE DATE NOT NULL,
	MODDATE DATE NOT NULL,	
	CATEGORY VARCHAR2(20)
);

COMMIT

--테이블조회
SELECT * FROM QA_BOARD;

--글번호 시퀀스(만든 적 있는 시퀀드 아이디라서 여기서 발번 안됨)
--CREATE SEQUENCE BOARDNOSQ NOCACHE;

--질문번호 시퀀스(새로운 글에만 번호 부여, 만든 적 있는 시퀀드 아이디라서 여기서 발번 안됨)
CREATE SEQUENCE GROUPNOSQ NOCACHE;

--질문 데이터 등록1
INSERT INTO QA_BOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '제목', '질문이다.', 'user01', SYSDATE, SYSDATE, '기타문의');

--테이블 삭제
--DROP TABLE QA_BOARD;

--질문 데이터 등록2
INSERT INTO QA_BOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '제목2', '질문이다.', 'user112', SYSDATE, SYSDATE, '계정문의');



--답글 등록1(시퀀스의.NEXTVAL 초기화를 못해서 9로 진행)
INSERT INTO QA_BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM QA_BOARD WHERE BOARDNO=9),
	(SELECT GROUPSQ FROM QA_BOARD WHERE BOARDNO=9)+1,
	(SELECT TITLETAB FROM QA_BOARD WHERE BOARDNO=9)+1,
	'RE:답글이다', '1번의 답글이다', 'admin555', SYSDATE, SYSDATE, '계정문의'
);

--답글 등록2
INSERT INTO QA_BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM QA_BOARD WHERE BOARDNO=10),
	(SELECT GROUPSQ FROM QA_BOARD WHERE BOARDNO=10)+1,
	(SELECT TITLETAB FROM QA_BOARD WHERE BOARDNO=10)+1,
	'RE:답글이다', '2번의 답글이다', 'admin555', SYSDATE, SYSDATE, '계정문의'
);

--질문 내림차순, 답글 오름차순
SELECT * FROM QA_BOARD
ORDER BY GROUPNO DESC, GROUPSQ;



--답글의 답글 작성(BOARDNO가 12)
INSERT INTO QA_BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM QA_BOARD WHERE BOARDNO=12),
	(SELECT GROUPSQ FROM QA_BOARD WHERE BOARDNO=12)+1,
	(SELECT TITLETAB FROM QA_BOARD WHERE BOARDNO=12)+1,
	'RE:RE:답글의 답글이다', '1번의 답글의 답글이다', 'user01', SYSDATE, SYSDATE, '계정문의'
);

COMMIT

