DROP TABLE MEMBER;
DROP SEQUENCE MYNOSEQ;

CREATE SEQUENCE MYNOSEQ NOCACHE;

CREATE TABLE MEMBER(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(500) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYPOSTCODE NUMBER NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYADD_ADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYEMAIL VARCHAR2(100) NOT NULL,
	MYGENDER VARCHAR2(2) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(50) NOT NULL,
	MYTYPE VARCHAR2(10),
	CONSTRAINT MEMBER_PK PRIMARY KEY(MYNO),
	CONSTRAINT MEMBER_UQ_ID UNIQUE(MYID),
	CONSTRAINT MEMBER_UQ_PHONE UNIQUE(MYPHONE),
	CONSTRAINT MEMBER_UQ_EMAIL UNIQUE(MYEMAIL),
	CONSTRAINT MEMBER_GENDER_CHK CHECK(MYGENDER IN('F','M')),
	CONSTRAINT MEMBER_ENABLED_CHK CHECK(MYENABLED IN('Y','N'))
);

INSERT INTO MEMBER VALUES(MYNOSEQ.NEXTVAL,'ADMIN','ADMIN1234','관리자','12345','관리시 관리구 관리동','101-1002','010-6335-2631',
							'ADMIN@MYMEMBER.COM','F','Y','ADMIN');
							
INSERT INTO MEMBER VALUES(MYNOSEQ.NEXTVAL,'USER','USER','USER','12345','관리시 관리구 관리동','101-1002','010-6333-2631',
							'USER@MYMEMBER.COM','F','Y','USER');

SELECT * FROM MEMBER;