DROP TABLE MEMBER;
DROP SEQUENCE MYNOSEQ;

CREATE SEQUENCE MYNOSEQ NOCACHE;

CREATE TABLE MEMBER(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(500) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYPOSTCODE VARCHAR2(20) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYADD_ADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYEMAIL VARCHAR2(100) NOT NULL,
	MYGENDER VARCHAR2(2) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(50) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(MYNO),
	CONSTRAINT MEMBER_UQ_ID UNIQUE(MYID),
	CONSTRAINT MEMBER_UQ_PHONE UNIQUE(MYPHONE),
	CONSTRAINT MEMBER_UQ_EMAIL UNIQUE(MYEMAIL),
	CONSTRAINT MEMBER_GENDER_CHK CHECK(MYGENDER IN('F','M')),
	CONSTRAINT MEMBER_ENABLED_CHK CHECK(MYENABLED IN('Y','N'))
);

/* 회원가입 DB */
CREATE TABLE MEMBER(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYPOSTCODE VARCHAR2(20) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYADD_ADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYGENDER VARCHAR2(2) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(50) NOT NULL,
	CONSTRAINT MEMBER_GENDER_CHK CHECK(MYGENDER IN('F','M')),
	CONSTRAINT MEMBER_ENABLED_CHK CHECK(MYENABLED IN('Y','N'))
);


INSERT INTO MEMBER VALUES(MYNOSEQ.NEXTVAL,'ADMIN','관리자','ADMIN1234','12345','관리시 관리구 관리동','101-1002','010-6335-2631',
							'F', 'Y','ADMIN');
							
SELECT * FROM MEMBER;





/*--------------------------------------------------------------------------------------------------*/
INSERT INTO MEMBER VALUES(MYNOSEQ.NEXTVAL,'ADMIN','ADMIN1234','관리자','12345','관리시 관리구 관리동','101-1002','010-6335-2631',
							'ADMIN@MYMEMBER.COM','F','Y','ADMIN');
							
INSERT INTO MEMBER VALUES(MYNOSEQ.NEXTVAL,'USER1','USER1234','김은미','경기도 평택시','010-6325-2631',
							'USER1@MYMEMBER.COM','Y','USER');

INSERT INTO MEMBER
VALUES(MYNOSEQ.NEXTVAL, 'ADMIN', 'ADMIN1234', '관리자', '관리시 관리구 관리동', '010-1234-5678',
	   'ADMIN@MYMEMBER.COM', 'Y', 'ADMIN');
	   

							

SELECT * FROM MEMBER;